# This file has the info necessary for the setup of the Crowdin github Action.
# The info was taken from the page of the github Action: https://github.com/marketplace/actions/crowdin-action

# By default, the Action will look for the crowdin.yml file in the root of the repository, so I put this file in there.
# Feel free to discuss moving it elsewhere if you can think of a better location.
# You can specify a different path using the "config" option in this file.

"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "Yafc/Data/locale/en/*.cfg",
    "dest": "%file_name%.ini",
    "translation": "Yafc/Data/locale/%two_letters_code%/%file_name%.cfg"
  }
]
